global:
  scrape_interval: 15s  # как часто собирать метрики

scrape_configs:
  - job_name: 'node-todo-app'
    static_configs:
      - targets: ['host.docker.internal:8080']

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'
